# fly.toml app configuration file generated for noppelbot on 2024-12-12T22:03:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'noppelbot'
primary_region = 'fra'

[build]

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
